# Generated by Django 6.0.3 on 2026-08-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netwellapp', '0002_blogpost_static_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a featured image (recommended). Takes priority over the legacy filename below.', null=True, upload_to='blog/'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly price in KES (e.g. 2500). Leave blank to hide.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_filename',
            field=models.CharField(blank=True, default='', help_text='Legacy: filename of a bundled image in /public/images/blog/. Prefer the upload field above.', max_length=300),
        ),
    ]
