# Generated by Django 6.0.3 on 2026-10-09 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(default='unit', max_length=30)),
                ('current_stock', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_team', models.BooleanField(default=False)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_location', models.CharField(blank=True, max_length=255)),
                ('unit_number', models.CharField(blank=True, max_length=50)),
                ('work_type', models.CharField(choices=[('new_installation', 'New Installation'), ('router_installation', 'Router Installation'), ('fiber_repair', 'Fiber Repair'), ('cable_replacement', 'Cable Replacement'), ('router_configuration', 'Router Configuration'), ('site_survey', 'Site Survey'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=30)),
                ('work_performed', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('follow_up', 'Follow-up Required'), ('customer_not_available', 'Customer Not Available')], max_length=30)),
                ('pending_reason', models.CharField(blank=True, choices=[('equipment_unavailable', 'Equipment unavailable'), ('customer_absent', 'Customer absent'), ('power_issue', 'Power issue'), ('network_issue', 'Network issue'), ('other', 'Other')], max_length=30, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('inventory_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='team_reports', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='reports.material')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='reports.report')),
            ],
            options={
                'unique_together': {('report', 'material')},
            },
        ),
        migrations.AddField(
            model_name='report',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='reports', through='reports.ReportMaterial', to='reports.material'),
        ),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.report')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
